namespace Rewndly.Infrastructure.ExternalServices.Tmdb;

public sealed record TmdbEndpointDefinition(string OperationId, string Path, string Summary);

public static class TmdbEndpointCatalog
{
    public static readonly IReadOnlyList<TmdbEndpointDefinition> PublicReadOnlyEndpoints = [
        new("collection-details", "collection/{collection_id}", "Details"),
        new("collection-images", "collection/{collection_id}/images", "Images"),
        new("collection-translations", "collection/{collection_id}/translations", "Translations"),
        new("company-details", "company/{company_id}", "Details"),
        new("company-alternative-names", "company/{company_id}/alternative_names", "Alternative Names"),
        new("company-images", "company/{company_id}/images", "Images"),
        new("configuration-countries", "configuration/countries", "Countries"),
        new("credit-details", "credit/{credit_id}", "Details"),
        new("discover-movie", "discover/movie", "Movie"),
        new("discover-tv", "discover/tv", "TV"),
        new("find-by-id", "find/{external_id}", "Find By ID"),
        new("genre-movie-list", "genre/movie/list", "Movie List"),
        new("genre-tv-list", "genre/tv/list", "TV List"),
        new("keyword-details", "keyword/{keyword_id}", "Details"),
        new("keyword-movies", "keyword/{keyword_id}/movies", "Movies"),
        new("list-details", "list/{list_id}", "Details"),
        new("list-check-item-status", "list/{list_id}/item_status", "Check Item Status"),
        new("movie-details", "movie/{movie_id}", "Details"),
        new("movie-alternative-titles", "movie/{movie_id}/alternative_titles", "Alternative Titles"),
        new("movie-changes", "movie/{movie_id}/changes", "Changes"),
        new("movie-credits", "movie/{movie_id}/credits", "Credits"),
        new("movie-external-ids", "movie/{movie_id}/external_ids", "External IDs"),
        new("movie-images", "movie/{movie_id}/images", "Images"),
        new("movie-keywords", "movie/{movie_id}/keywords", "Keywords"),
        new("movie-lists", "movie/{movie_id}/lists", "Lists"),
        new("movie-recommendations", "movie/{movie_id}/recommendations", "Recommendations"),
        new("movie-release-dates", "movie/{movie_id}/release_dates", "Release Dates"),
        new("movie-reviews", "movie/{movie_id}/reviews", "Reviews"),
        new("movie-similar", "movie/{movie_id}/similar", "Similar"),
        new("movie-translations", "movie/{movie_id}/translations", "Translations"),
        new("movie-videos", "movie/{movie_id}/videos", "Videos"),
        new("movie-watch-providers", "movie/{movie_id}/watch/providers", "Watch Providers"),
        new("changes-movie-list", "movie/changes", "Movie List"),
        new("movie-now-playing-list", "movie/now_playing", "Now Playing"),
        new("movie-popular-list", "movie/popular", "Popular"),
        new("movie-top-rated-list", "movie/top_rated", "Top Rated"),
        new("movie-upcoming-list", "movie/upcoming", "Upcoming"),
        new("network-details", "network/{network_id}", "Details"),
        new("details-copy", "network/{network_id}/alternative_names", "Alternative Names"),
        new("alternative-names-copy", "network/{network_id}/images", "Images"),
        new("person-details", "person/{person_id}", "Details"),
        new("person-changes", "person/{person_id}/changes", "Changes"),
        new("person-combined-credits", "person/{person_id}/combined_credits", "Combined Credits"),
        new("person-external-ids", "person/{person_id}/external_ids", "External IDs"),
        new("person-images", "person/{person_id}/images", "Images"),
        new("person-movie-credits", "person/{person_id}/movie_credits", "Movie Credits"),
        new("person-tagged-images", "person/{person_id}/tagged_images", "Tagged Images"),
        new("translations", "person/{person_id}/translations", "Translations"),
        new("person-tv-credits", "person/{person_id}/tv_credits", "TV Credits"),
        new("changes-people-list", "person/changes", "People List"),
        new("person-popular-list", "person/popular", "Popular"),
        new("review-details", "review/{review_id}", "Details"),
        new("search-collection", "search/collection", "Collection"),
        new("search-company", "search/company", "Company"),
        new("search-keyword", "search/keyword", "Keyword"),
        new("search-movie", "search/movie", "Movie"),
        new("search-multi", "search/multi", "Multi"),
        new("search-person", "search/person", "Person"),
        new("search-tv", "search/tv", "TV"),
        new("trending-all", "trending/all/{time_window}", "All"),
        new("trending-movies", "trending/movie/{time_window}", "Movies"),
        new("trending-people", "trending/person/{time_window}", "People"),
        new("trending-tv", "trending/tv/{time_window}", "TV"),
        new("tv-series-details", "tv/{series_id}", "Details"),
        new("tv-series-aggregate-credits", "tv/{series_id}/aggregate_credits", "Aggregate Credits"),
        new("tv-series-alternative-titles", "tv/{series_id}/alternative_titles", "Alternative Titles"),
        new("tv-series-changes", "tv/{series_id}/changes", "Changes"),
        new("tv-series-content-ratings", "tv/{series_id}/content_ratings", "Content Ratings"),
        new("tv-series-credits", "tv/{series_id}/credits", "Credits"),
        new("tv-series-episode-groups", "tv/{series_id}/episode_groups", "Episode Groups"),
        new("tv-series-external-ids", "tv/{series_id}/external_ids", "External IDs"),
        new("tv-series-images", "tv/{series_id}/images", "Images"),
        new("tv-series-keywords", "tv/{series_id}/keywords", "Keywords"),
        new("lists-copy", "tv/{series_id}/lists", "Lists"),
        new("tv-series-recommendations", "tv/{series_id}/recommendations", "Recommendations"),
        new("tv-series-reviews", "tv/{series_id}/reviews", "Reviews"),
        new("tv-series-screened-theatrically", "tv/{series_id}/screened_theatrically", "Screened Theatrically"),
        new("tv-season-details", "tv/{series_id}/season/{season_number}", "Details"),
        new("tv-season-aggregate-credits", "tv/{series_id}/season/{season_number}/aggregate_credits", "Aggregate Credits"),
        new("tv-season-credits", "tv/{series_id}/season/{season_number}/credits", "Credits"),
        new("tv-episode-details", "tv/{series_id}/season/{season_number}/episode/{episode_number}", "Details"),
        new("tv-episode-credits", "tv/{series_id}/season/{season_number}/episode/{episode_number}/credits", "Credits"),
        new("tv-episode-external-ids", "tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids", "External IDs"),
        new("tv-episode-images", "tv/{series_id}/season/{season_number}/episode/{episode_number}/images", "Images"),
        new("tv-episode-translations", "tv/{series_id}/season/{season_number}/episode/{episode_number}/translations", "Translations"),
        new("tv-episode-videos", "tv/{series_id}/season/{season_number}/episode/{episode_number}/videos", "Videos"),
        new("tv-season-external-ids", "tv/{series_id}/season/{season_number}/external_ids", "External IDs"),
        new("tv-season-images", "tv/{series_id}/season/{season_number}/images", "Images"),
        new("tv-season-translations", "tv/{series_id}/season/{season_number}/translations", "Translations"),
        new("tv-season-videos", "tv/{series_id}/season/{season_number}/videos", "Videos"),
        new("tv-season-watch-providers", "tv/{series_id}/season/{season_number}/watch/providers", "Watch Providers"),
        new("tv-series-similar", "tv/{series_id}/similar", "Similar"),
        new("tv-series-translations", "tv/{series_id}/translations", "Translations"),
        new("tv-series-videos", "tv/{series_id}/videos", "Videos"),
        new("tv-series-watch-providers", "tv/{series_id}/watch/providers", "Watch Providers"),
        new("tv-series-airing-today-list", "tv/airing_today", "Airing Today"),
        new("changes-tv-list", "tv/changes", "TV List"),
        new("tv-episode-changes-by-id", "tv/episode/{episode_id}/changes", "Changes"),
        new("tv-episode-group-details", "tv/episode_group/{tv_episode_group_id}", "Details"),
        new("tv-series-on-the-air-list", "tv/on_the_air", "On The Air"),
        new("tv-series-popular-list", "tv/popular", "Popular"),
        new("tv-season-changes-by-id", "tv/season/{season_id}/changes", "Changes"),
        new("tv-series-top-rated-list", "tv/top_rated", "Top Rated"),
        new("watch-providers-movie-list", "watch/providers/movie", "Movie Providers"),
        new("watch-providers-available-regions", "watch/providers/regions", "Available Regions"),
        new("watch-provider-tv-list", "watch/providers/tv", "TV Providers"),
    ];
}
