// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rewndly.Infrastructure.Persistence;

#nullable disable

namespace Rewndly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rewndly.Domain.Admin.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_type");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_admin_audit_logs_action");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_audit_logs_admin_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_admin_audit_logs_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_admin_audit_logs_target_type_target_id");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Analytics.CloudflareDailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long?>("HumanPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("human_page_views");

                    b.Property<long?>("HumanVisits")
                        .HasColumnType("bigint")
                        .HasColumnName("human_visits");

                    b.Property<long>("PageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("page_views");

                    b.Property<long>("Requests")
                        .HasColumnType("bigint")
                        .HasColumnName("requests");

                    b.Property<long>("Threats")
                        .HasColumnType("bigint")
                        .HasColumnName("threats");

                    b.Property<long>("Uniques")
                        .HasColumnType("bigint")
                        .HasColumnName("uniques");

                    b.HasKey("Id")
                        .HasName("pk_cloudflare_daily_snapshots");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_cloudflare_daily_snapshots_date");

                    b.ToTable("cloudflare_daily_snapshots", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Events.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("event_type");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_activity_events_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_activity_events_event_type");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_activity_events_movie_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_activity_events_series_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_activity_events_user_id");

                    b.ToTable("activity_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_activity_events_optional_media", "((movie_id IS NULL AND series_id IS NULL AND media_type IS NULL) OR (movie_id IS NOT NULL AND series_id IS NULL AND media_type = 'Movie') OR (movie_id IS NULL AND series_id IS NOT NULL AND media_type = 'Series'))");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Events.SystemEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_system_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_system_events_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_system_events_event_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_system_events_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_system_events_entity_type_entity_id");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Friends.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_friendships_receiver_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_friendships_requester_id");

                    b.HasIndex("RequesterId", "ReceiverId")
                        .IsUnique()
                        .HasDatabaseName("ix_friendships_requester_id_receiver_id");

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("ck_friendships_not_self", "requester_id <> receiver_id");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Friends.FriendshipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.HasKey("Id")
                        .HasName("pk_friendship_requests");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_friendship_requests_receiver_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_friendship_requests_requester_id");

                    b.HasIndex("RequesterId", "ReceiverId")
                        .IsUnique()
                        .HasDatabaseName("ix_friendship_requests_requester_id_receiver_id");

                    b.ToTable("friendship_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_friendship_requests_not_self", "requester_id <> receiver_id");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Library.UserMediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("WatchedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("watched_at");

                    b.HasKey("Id")
                        .HasName("pk_user_media_items");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_user_media_items_movie_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_user_media_items_series_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_user_media_items_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_media_items_user_id");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_media_items_user_id_movie_id")
                        .HasFilter("movie_id IS NOT NULL");

                    b.HasIndex("UserId", "SeriesId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_media_items_user_id_series_id")
                        .HasFilter("series_id IS NOT NULL");

                    b.ToTable("user_media_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_media_items_one_media", "((movie_id IS NOT NULL AND series_id IS NULL AND media_type = 'Movie') OR (movie_id IS NULL AND series_id IS NOT NULL AND media_type = 'Series'))");

                            t.HasCheckConstraint("ck_user_media_items_rating_range", "(rating IS NULL OR (rating >= 1 AND rating <= 10))");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Lists.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_lists");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_lists_is_deleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lists_user_id");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_lists_visibility");

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Lists.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.HasKey("Id")
                        .HasName("pk_list_items");

                    b.HasIndex("ListId")
                        .HasDatabaseName("ix_list_items_list_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_list_items_movie_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_list_items_series_id");

                    b.HasIndex("ListId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("ix_list_items_list_id_movie_id")
                        .HasFilter("movie_id IS NOT NULL");

                    b.HasIndex("ListId", "SeriesId")
                        .IsUnique()
                        .HasDatabaseName("ix_list_items_list_id_series_id")
                        .HasFilter("series_id IS NOT NULL");

                    b.ToTable("list_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_list_items_one_media", "((movie_id IS NOT NULL AND series_id IS NULL AND media_type = 'Movie') OR (movie_id IS NULL AND series_id IS NOT NULL AND media_type = 'Series'))");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Media.ExternalMediaRankingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BackdropUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backdrop_url");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_url");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("RankingKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ranking_key");

                    b.Property<decimal?>("RankingScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("ranking_score");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<decimal?>("VoteAverage")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("vote_average");

                    b.HasKey("Id")
                        .HasName("pk_external_media_ranking_items");

                    b.HasIndex("MediaType", "RankingKey", "ExpiresAt")
                        .HasDatabaseName("ix_external_media_ranking_items_media_type_ranking_key_expires");

                    b.HasIndex("MediaType", "RankingKey", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_external_media_ranking_items_media_type_ranking_key_rank");

                    b.HasIndex("MediaType", "RankingKey", "TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_media_ranking_items_media_type_ranking_key_tmdb_id");

                    b.ToTable("external_media_ranking_items", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.ExternalMediaRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<decimal?>("Scale")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("scale");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<decimal?>("Value")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("value");

                    b.Property<int?>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("Id")
                        .HasName("pk_external_media_ratings");

                    b.HasIndex("MediaType", "TmdbId", "ExpiresAt")
                        .HasDatabaseName("ix_external_media_ratings_media_type_tmdb_id_expires_at");

                    b.HasIndex("MediaType", "TmdbId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_external_media_ratings_media_type_tmdb_id_source");

                    b.ToTable("external_media_ratings", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("TmdbId", "MediaType")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_tmdb_id_media_type");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backdrop_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("overview");

                    b.Property<decimal?>("Popularity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("popularity");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_path");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("VoteAverage")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("vote_average");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_movies_release_date");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_movies_title");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_tmdb_id");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.MovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.HasKey("Id")
                        .HasName("pk_movie_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_movie_genres_genre_id");

                    b.HasIndex("MovieId", "GenreId")
                        .IsUnique()
                        .HasDatabaseName("ix_movie_genres_movie_id_genre_id");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backdrop_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("FirstAirDate")
                        .HasColumnType("date")
                        .HasColumnName("first_air_date");

                    b.Property<DateOnly?>("LastAirDate")
                        .HasColumnType("date")
                        .HasColumnName("last_air_date");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_episodes");

                    b.Property<int?>("NumberOfSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_seasons");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_name");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("overview");

                    b.Property<decimal?>("Popularity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("popularity");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_path");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("VoteAverage")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("vote_average");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("FirstAirDate")
                        .HasDatabaseName("ix_series_first_air_date");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_series_name");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_tmdb_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.SeriesGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.HasKey("Id")
                        .HasName("pk_series_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_series_genres_genre_id");

                    b.HasIndex("SeriesId", "GenreId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_genres_series_id_genre_id");

                    b.ToTable("series_genres", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Media.WikidataEnrichmentCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AwardsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("awards_json");

                    b.Property<string>("BioExtract")
                        .HasColumnType("text")
                        .HasColumnName("bio_extract");

                    b.Property<string>("BioSourceTitle")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("bio_source_title");

                    b.Property<string>("BioSourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio_source_url");

                    b.Property<string>("BioThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio_thumbnail_url");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<string>("WikidataId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wikidata_id");

                    b.HasKey("Id")
                        .HasName("pk_wikidata_enrichment_cache");

                    b.HasIndex("EntityType", "TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_wikidata_enrichment_cache_entity_type_tmdb_id");

                    b.ToTable("wikidata_enrichment_cache", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<bool>("ContainsSpoilers")
                        .HasColumnType("boolean")
                        .HasColumnName("contains_spoilers");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<decimal?>("RatingSnapshot")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating_snapshot");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_reviews_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_reviews_is_deleted");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_reviews_movie_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_reviews_series_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_reviews_visibility");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_one_media", "((movie_id IS NOT NULL AND series_id IS NULL AND media_type = 'Movie') OR (movie_id IS NULL AND series_id IS NOT NULL AND media_type = 'Series'))");

                            t.HasCheckConstraint("ck_reviews_rating_snapshot_range", "(rating_snapshot IS NULL OR (rating_snapshot >= 1 AND rating_snapshot <= 10))");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Users.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_verification_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Users.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requested_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UsedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("used_by_ip");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_password_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_revoked_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Users.TmdbAccountConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("ProtectedSessionId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("protected_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("TmdbAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_account_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_tmdb_account_connections");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_tmdb_account_connections_revoked_at");

                    b.HasIndex("TmdbAccountId")
                        .HasDatabaseName("ix_tmdb_account_connections_tmdb_account_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tmdb_account_connections_user_id")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("tmdb_account_connections", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Users.TmdbAuthRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("request_token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tmdb_auth_requests");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_tmdb_auth_requests_expires_at");

                    b.HasIndex("RequestTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tmdb_auth_requests_request_token_hash");

                    b.HasIndex("UsedAt")
                        .HasDatabaseName("ix_tmdb_auth_requests_used_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tmdb_auth_requests_user_id");

                    b.ToTable("tmdb_auth_requests", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_admin_id");

                    b.Property<string>("DisableReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disable_reason");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("DisabledByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("disabled_by_admin_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DeletedByAdminId")
                        .HasDatabaseName("ix_users_deleted_by_admin_id");

                    b.HasIndex("DisabledByAdminId")
                        .HasDatabaseName("ix_users_disabled_by_admin_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted");

                    b.HasIndex("IsDisabled")
                        .HasDatabaseName("ix_users_is_disabled");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_not_empty", "length(email) > 0");

                            t.HasCheckConstraint("ck_users_username_not_empty", "length(username) > 0");
                        });
                });

            modelBuilder.Entity("Rewndly.Domain.Users.UserPrivacySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("profile_visibility");

                    b.Property<bool>("ShowActivity")
                        .HasColumnType("boolean")
                        .HasColumnName("show_activity");

                    b.Property<bool>("ShowStats")
                        .HasColumnType("boolean")
                        .HasColumnName("show_stats");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_privacy_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_privacy_settings_user_id");

                    b.ToTable("user_privacy_settings", (string)null);
                });

            modelBuilder.Entity("Rewndly.Domain.Admin.AdminAuditLog", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_audit_logs_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Rewndly.Domain.Events.ActivityEvent", b =>
                {
                    b.HasOne("Rewndly.Domain.Media.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_activity_events_movies_movie_id");

                    b.HasOne("Rewndly.Domain.Media.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_activity_events_series_series_id");

                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_events_users_user_id");

                    b.Navigation("Movie");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Events.SystemEvent", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_system_events_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Friends.Friendship", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_receiver_id");

                    b.HasOne("Rewndly.Domain.Users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_requester_id");

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Rewndly.Domain.Friends.FriendshipRequest", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendship_requests_users_receiver_id");

                    b.HasOne("Rewndly.Domain.Users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendship_requests_users_requester_id");

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Rewndly.Domain.Library.UserMediaItem", b =>
                {
                    b.HasOne("Rewndly.Domain.Media.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_media_items_movies_movie_id");

                    b.HasOne("Rewndly.Domain.Media.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_media_items_series_series_id");

                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_media_items_users_user_id");

                    b.Navigation("Movie");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Lists.List", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Lists.ListItem", b =>
                {
                    b.HasOne("Rewndly.Domain.Lists.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_items_lists_list_id");

                    b.HasOne("Rewndly.Domain.Media.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_list_items_movies_movie_id");

                    b.HasOne("Rewndly.Domain.Media.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_list_items_series_series_id");

                    b.Navigation("List");

                    b.Navigation("Movie");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Rewndly.Domain.Media.MovieGenre", b =>
                {
                    b.HasOne("Rewndly.Domain.Media.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_genres_genre_id");

                    b.HasOne("Rewndly.Domain.Media.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_movies_movie_id");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Rewndly.Domain.Media.SeriesGenre", b =>
                {
                    b.HasOne("Rewndly.Domain.Media.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_genres_genres_genre_id");

                    b.HasOne("Rewndly.Domain.Media.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_genres_series_series_id");

                    b.Navigation("Genre");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Rewndly.Domain.Reviews.Review", b =>
                {
                    b.HasOne("Rewndly.Domain.Media.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reviews_movies_movie_id");

                    b.HasOne("Rewndly.Domain.Media.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reviews_series_series_id");

                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");

                    b.Navigation("Movie");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.EmailVerificationToken", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.PasswordResetToken", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.TmdbAccountConnection", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tmdb_account_connections_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.TmdbAuthRequest", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tmdb_auth_requests_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.User", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "DeletedByAdmin")
                        .WithMany()
                        .HasForeignKey("DeletedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_deleted_by_admin_id");

                    b.HasOne("Rewndly.Domain.Users.User", "DisabledByAdmin")
                        .WithMany()
                        .HasForeignKey("DisabledByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_disabled_by_admin_id");

                    b.Navigation("DeletedByAdmin");

                    b.Navigation("DisabledByAdmin");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.UserPrivacySettings", b =>
                {
                    b.HasOne("Rewndly.Domain.Users.User", "User")
                        .WithOne("PrivacySettings")
                        .HasForeignKey("Rewndly.Domain.Users.UserPrivacySettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_privacy_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rewndly.Domain.Users.User", b =>
                {
                    b.Navigation("PrivacySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
