namespace Rewndly.Domain.Events;

public enum SystemEventType
{
    UserRegistered = 1,
    UserLoggedIn = 2,
    UserLoginFailed = 3,
    UserLoggedOut = 4,
    LogoutAll = 5,
    PasswordResetRequested = 6,
    PasswordResetCompleted = 7,
    EmailVerificationRequested = 8,
    EmailVerified = 9,
    MovieSearchPerformed = 10,
    SeriesSearchPerformed = 11,
    RefreshTokenRotated = 12,
    RefreshTokenReused = 13,
    RefreshTokenReuseDetected = 14,
    AdminUserDisabled = 15,
    AdminUserEnabled = 16,
    AdminUserSoftDeleted = 17,
    AdminRoleChanged = 18,
    LibraryItemCreated = 19,
    LibraryItemUpdated = 20,
    LibraryItemDeleted = 21,
    ReviewCreated = 22,
    ReviewUpdated = 23,
    ReviewDeleted = 24,
    ListCreated = 25,
    ListUpdated = 26,
    ListDeleted = 27,
    ListItemAdded = 28,
    ListItemRemoved = 29,
    FriendshipCreated = 30,
    FriendshipDeleted = 31,
    AdminViewedDashboard = 32,
    AdminViewedUser = 33,
    AdminReviewSoftDeleted = 34,
    AdminListSoftDeleted = 35,
    PasswordChanged = 36,
    ExternalProviderDisabled = 37,
    ExternalProviderRecovered = 38
}
